# -*- coding: utf-8 -*-
"""LabTask2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_fAeXc453UUSqqcDN4U-DllxwZrkKNeT
"""

open = ["[","{","("]
close = ["]","}",")"]
def function(myStr):
    stack = []
    for i in myStr:
        if i in open:
            stack.append(i)
        elif i in close:
            pos = close.index(i)
            if ((len(stack) > 0) and (open[pos] == stack[len(stack)-1])):
                stack.pop()
            else:
                return "Unbalanced"
    if len(stack) == 0:
        return "Balanced"
    else:
        return "Unbalanced"

x=input("Enter equation: ")
equation = x
print("The eq '", x,"' is ", function(equation))

