# -*- coding: utf-8 -*-
"""LabTask1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nhixM7bPWfHFb-kqx7zPJiCiAp2Gu0k5
"""

string=input("Enter text: ")
rev=string[::-1]
stack=[]
for letters in string:
    stack.append(letters)
print(stack)
if (rev==string):
    print("Palindrome")
else:
    print("Not palindrome")



